version: '3'

volumes:
  frontend_volume_node_modules:

services:
  node:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    tty: true
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./:/app:cached
      - frontend_volume_node_modules:/app/node_modules
    command: yarn dev
