version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    tty: true
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn dev
