version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./:/app
    working_dir: '/app'
    networks:
      - default
      - mdcloud-local
    environment:
      NODE_ENV: development
    command: sh -c "npm run dev"

networks:
  mdcloud-local:
    external: true
