version: '3'

volumes:
  frontend_volume_node_modules:

services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    tty: true
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./:/app:cached
      - frontend_volume_node_modules:/app/node_modules
    command: npm run dev
