name: Push Action

on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - '18.7.0'

    name: Node ${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: |
          npm install -g yarn
          yarn install

      - name: Eslint & Prettier
        run: yarn run lint

      - name: Test
        run: yarn run test
